<?php

/**
 * @file
 * Primary module hooks for Silly Text Formatters module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function silly_text_formatters_theme($existing, $type, $theme, $path)
{
  return [
    'silly_tooltip' => [
      'variables' => [
        'text' => NULL,
        'tooltip' => NULL,
      ],
      'template' => 'silly-tooltip',
    ],
  ];
}
